domain: cawfeecake.github.io
url: https://cawfeecake.github.io
baseurl: /test-gh-pages
permalink: /:title  # title is filename
markdown: kramdown
title: WX Data
description: automatically update weather information
