#remote-theme: kitian616/jekyll-TeXt-theme
title: WX Data
description: automatically update weather information

domain: cawfeecake.github.io
url: https://cawfeecake.github.io
baseurl: /test-gh-pages/
