domain: cawfeecake.github.io
url: https://cawfeecake.github.io
baseurl: /test-gh-pages
permalink: /:title # online discussion says a trailing "/" is required, but w/ testing that doesn't seem to be the case
markdown: GFM
title: WX Data
description: automatically update weather information
