name: Get WX data

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # e.g. - cron:  '30 5,17 * * *'
    # every 20th minute
    - cron:  '*/20 * * * *'

jobs:
  upload-wx-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          let api_requests=0
          while read -r line
          do
            curl -s --header "Authorization: $AVWX_TOKEN" https://avwx.rest/api/metar/$line
            ((api_requests+=1))
          done < <(printf "%s" "$(< airports.txt)")
          # TODO can I connect the /$number in cron string to the equation here?
          request_rate_per_day=$((24*((60/20))*$api_requests))
          if [ "$request_rate_per_day" -gt "4000" ]; then
            # 55 @ every 20 minutes
            echo "::warning::will perform $request_rate_per_day request per day; above free-tier limit of 4000"
          else
            echo "::debug::under per day request limit"
          fi
        env:
          AVWX_TOKEN: ${{ secrets.AVWX_TOKEN }}
