name: Get WX data

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # e.g. - cron:  '30 5,17 * * *'
    # every 20th minute
    - cron:  '*/20 * * * *'

jobs:
  upload-wx-assets:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s --header "Authorization: $AVWX_TOKEN" https://avwx.rest/api/metar/KPAE
        env:
          AVWX_TOKEN: ${{ secrets.AVWX_TOKEN }}
