name: Get WX data

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # e.g. - cron:  '30 5,17 * * *'
    # every 20th minute
    - cron:  '*/20 * * * *'

jobs:
  upload-wx-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          api_requests=0
          while read -r airport
          do
            curl -s --header "Authorization: $AVWX_TOKEN" "https://avwx.rest/api/metar/$airport" | jq .
            echo
            # dev note: let returns exit code 1 when expression evals to 0; x++ returns 0 if x == 0 b/c it's post-increment
            let ++api_requests
          done < <(printf "%s" "$(< airports.txt)")
          echo "number of api requests: $api_requests"
        env:
          AVWX_TOKEN: ${{ secrets.AVWX_TOKEN }}
