name: Write WX data to Pages

on:
  workflow_run:
    workflows: [Get WX data]
    types: [completed]

jobs:
  add-weather-data-to-pages:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: download weather data from upstream workflow run
        run: |
          gh run download ${{ github.event.workflow_run.id }} -n weather-data -D weather-data
        env:
          GH_TOKEN: ${{ github.token }}
