name: Write WX data to Pages

on:
  workflow_run:
    workflows: [Get WX data]
    types: [completed]

jobs:
  debug-github-context:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJSON(github) }}' | jq .
  add-weather-data-to-pages:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: download weather data from upstream workflow run
        run: |
          gh run download ${{ github.event.workflow_run.id }} -n weather-data -D weather-data
        env:
          GH_TOKEN: ${{ github.token }}
      - name: add weather data to GitHub Pages
        run: |
          touch weather.txt
          for file in weather-data/*.json; do
            jq -r '[ .station,.flight_rules,.altimeter.repr ] | join(" ")' $file >> weather.txt
            echo '' >> weather.txt
          done
      - name: create index.md from template
        shell: python
        run: |
          from string import Template

          with open('index.md', 'w') as output_file, open('_template.md', 'r') as template_file, open('weather.txt') as weather_file:
              template_data = {
                  'weather': weather_file.read(),
              }
              template = Template(template_file.read())
              result = template.substitute(template_data)
              output_file.write(result)
      - name: update weather _data file
        run: |
          UPDATE_TIME=$(date -u '+%a, %b %d, %Y - %r GMT') yq -i '.update_time = strenv(UPDATE_TIME)' _data/weather.yml
      - name: commit changes to branch
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          if git diff --quiet index.md; then
            echo "no changes; nothing to commit"
          else
            git add index.md
            git commit -m 'update Page with changed wx data'
            git push
          fi
  job-ran-if-not-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - run: |
          echo 'Check out DEBUG step; ...conclusion != '"'success'"
